### ISSUE TITLE
Incompatability with Pehkui

### ISSUE THREAD

**Issue by MagnaRose** [Fayenora/Robotics#2]
Installing Pehkui alongside Robotized will always result in a Crash with Exit Code 1.

I have tested this in a clean installed modpack with only the dependancies and Pehkui.
So I am certain its Pehkui and Robotized being incompatible .
Due to the Error being Exit Code 1 I am incapable of providing crash logs.

**Comment by Fayenora** [comment]
Thanks for the report, esp testing Pehkui & Robotics seperataly! Was able reproduce & fix it. The new version is available on modrinth. 
Compability with other mods should also have increased
