### ISSUE TITLE
Robotized crashes with Scorched Guns 2 installed

### ISSUE THREAD

**Issue by MagnaRose** [Fayenora/Robotics#3]
[crash-2024-09-22_12.54.16-server.txt](https://github.com/user-attachments/files/17089319/crash-2024-09-22_12.54.16-server.txt)

I am unsure what causes this exactly as I am not very good at reading crash reports.
The crash happens upon World generation or joining an already generated World.

**Comment by Fayenora** [comment]
Thanks for the report! Was able reproduce & fix it. The new version is available on modrinth. 
Compability with other mods should also have increased
